### ISSUE TITLE
Test errors when building from scratch

### ISSUE THREAD

**Issue by jlengrand** [Adyen/adyen-java-api-library#1073]
**Describe the bug**

When trying to build the library from scratch, I meet test errors.

**How to reproduce**

I could not find direct information on how to build the jar from scratch in the README or CONTRIBUTING, so I looked into the .github/workflows files. I found that the line that is used is

```mvn -B package --file pom.xml```

When running this on my machine, I get errors in the unit tests:

```
testDecryptionWithInvalidHmac(com.adyen.NexoCryptoTest)  Time elapsed: 0.019 sec  <<< ERROR!
java.lang.Exception: Unexpected exception, expected<com.adyen.terminal.security.exception.NexoCryptoException> but was<com.google.gson.JsonIOException>
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:30)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: com.google.gson.JsonIOException: Failed making field 'com.sun.org.apache.xerces.internal.jaxp.datatype.XMLGregorianCalendarImpl#eon' accessible; either increase its visibility or write a custom TypeAdapter for its declaring type.
....

Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.019 sec

Results :


Tests in error:
  testDecryptionWithInvalidHmac(com.adyen.NexoCryptoTest): Unexpected exception, expected<com.adyen.terminal.security.exception.NexoCryptoException> but was<com.google.gson.JsonIOException>
  testEncryptionWithInvalidSecurityKey(com.adyen.NexoCryptoTest): Unexpected exception, expected<com.adyen.terminal.security.exception.NexoCryptoException> but was<com.google.gson.JsonIOException>
  testDecryption(com.adyen.NexoCryptoTest): Failed making field 'com.sun.org.apache.xerces.internal.jaxp.datatype.XMLGregorianCalendarImpl#eon' accessible; either increase its visibility or write a custom TypeAdapter for its declaring type.
  testEncryption(com.adyen.NexoCryptoTest): Failed making field 'com.sun.org.apache.xerces.internal.jaxp.datatype.XMLGregorianCalendarImpl#eon' accessible; either increase its visibility or write a custom TypeAdapter for its declaring type.

Tests run: 319, Failures: 0, Errors: 4, Skipped: 3

```

**Expected behavior**

Not sure whether this is expected or not, am I missing something?

**Screenshots**

**Desktop (please complete the following information):**
 - Java Version: [x.y.z]
 - Library Version: [x.y.z]

**Additional context**

**Comment by jlengrand** [comment]
Ok, this seems to be a Java 17 problem. The issue disappears when compiling with Java 11

**Comment by jlengrand** [comment]
Ok, it's a Java 17 problem. Compiling with Java 11 solves it.
