### ISSUE TITLE
RecurringApi.deleteTokenForStoredPaymentDetails is returning java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by pauls-z** [Adyen/adyen-java-api-library#1123]
**Describe the bug**
Trying to delete stored credit card via RecurringApi.deleteTokenForStoredPaymentDetails is returning java.lang.IllegalArgumentException

```
java.lang.IllegalArgumentException: argument "content" is null
	at com.fasterxml.jackson.databind.ObjectMapper._assertNotNull(ObjectMapper.java:4829) ~[jackson-databind-2.13.4.2.jar:2.13.4.2]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3596) ~[jackson-databind-2.13.4.2.jar:2.13.4.2]
	at com.adyen.model.checkout.StoredPaymentMethodResource.fromJson(StoredPaymentMethodResource.java:623) ~[adyen-java-api-library-21.3.0.jar:?]
	at com.adyen.service.checkout.RecurringApi.deleteTokenForStoredPaymentDetails(RecurringApi.java:95) ~[adyen-java-api-library-21.3.0.jar:?]

```

**How to reproduce**
1. Store a credit card. Personally placed an order via CreditCards Web Component integration
2. Try removing the stored credit card afterwards

**Expected behavior**
No exception is thrown.

**Desktop (please complete the following information):**
 - Java Version: [17.0.4]
 - Library Version: [21.3.0]

**Comment by jillingk** [comment]
Hey @pauls-z,

Apologies for the delayed response, I guess we completely overlooked this issue. However good news, this issue is fixed in the new release! Let us know if you run into anything else during your integration.

Best, Jilling
Adyen
