### ISSUE TITLE
Some services are not extending ApiKeyAuthenticatedService anymore in latest version

### ISSUE THREAD

**Issue by ls-ronak-patel** [Adyen/adyen-java-api-library#1148]
**Java version**: 
**Library version**: 21.5.0
**Description**

- Some service classes (for e.g. [PosTerminalManagementApi](https://github.com/Adyen/adyen-java-api-library/blob/develop/src/main/java/com/adyen/service/PosTerminalManagementApi.java)) are not extending [ApiKeyAuthenticatedService](https://github.com/Adyen/adyen-java-api-library/blob/develop/src/main/java/com/adyen/ApiKeyAuthenticatedService.java) anymore in the latest version 21.5.0

- The equivalent class (used to be PosTerminalManagement) was extending ApiKeyAuthenticatedService in v19.0.0. 
- Are there any side effect of this? This service seems to throw 401 in v21.5.0 whereas it's working in v19.0.0

**Comment by ls-ronak-patel** [comment]
Our implementation was relying on isApiKeyRequired() method of ApiKeyAuthenticatedService to decide whether to set api key out not. Now these service classes directly implement Service, we have to find some other way.

**Comment by jillingk** [comment]
Hey @ls-ronak-patel,

Thanks for reaching out to us here. We've actually deprecated this class since every api call made should make use of our preferred way of authenticating anyways, which is with API-key. Which endpoints are you calling with basic auth? 

Best, Jilling
Adyen

**Comment by ls-ronak-patel** [comment]
Hi @jillingk `ClassicPlatformAccountApi` and `ClassicPlatformFundApi` from v21.5.0 still work with basic auth. I am working with Adyen test env so not sure it it's any different in prod.
(`ClassicPlatformAccountApi` has some serialization issues but at least it's not throwing 401)

**Comment by jillingk** [comment]
Hi @ls-ronak-patel,

Don't worry about this, we used to throw a warning for services that needed an API-key (and did not have basic auth supported) but we removed it quite a while ago, and that was the complete extent of it. For the classic endpoints you should still be able to use basic auth, just like you used to. 

Which kind of serialization issues are you seeing in the account API by the way? 

Best, Jilling
Adyen

**Comment by ls-ronak-patel** [comment]
@jillingk Thank you. Here is the stacktrace of the serialization error in v21.5.0. Seems like some enum value changed but the API response still returns old value. I checked that this enum has value 'DEFAULT' in v20.1.2

`j.l.IllegalArgumentException: Unexpected value 'DEFAULT'
	at c.a.m.m.PayoutScheduleResponse$ScheduleEnum.fromValue(PayoutScheduleResponse.java:101)
	at j.i.r.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java)
	at j.i.r.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at j.i.r.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at j.l.reflect.Method.invoke(Method.java:568)
	at c.f.j.d.i.AnnotatedMethod.callOnWith(AnnotatedMethod.java:117)
	at c.f.j.d.d.s.FactoryBasedEnumDeserializer.deserialize(FactoryBasedEnumDeserializer.java:183)
	at c.f.j.d.d.i.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at c.f.j.d.d.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at c.f.j.d.d.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at c.f.j.d.d.i.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at c.f.j.d.d.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at c.f.j.d.d.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at c.f.j.d.d.s.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359)
	at c.f.j.d.d.s.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
	at c.f.j.d.d.s.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
	at c.f.j.d.d.i.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at c.f.j.d.d.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at c.f.j.d.d.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at c.f.j.d.d.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at c.f.j.d.ObjectMapper._readMapAndClose(ObjectMapper.java:4730)
	at c.f.j.d.ObjectMapper.readValue(ObjectMapper.java:3677)
	at c.f.j.d.ObjectMapper.readValue(ObjectMapper.java:3645)
	at c.a.m.m.GetAccountHolderResponse.fromJson(GetAccountHolderResponse.java:587)
	at c.a.s.c.ClassicPlatformAccountApi.getAccountHolder(ClassicPlatformAccountApi.java:407)
	at c.a.s.c.ClassicPlatformAccountApi.getAccountHolder(ClassicPlatformAccountApi.java:391)`

**Comment by jillingk** [comment]
Hi @ls-ronak-patel,

Sorry to hear that this value was missing. I quickly opened a pr to add this value. These classic platform services are a bit old so we're doing our best to improve it and make it usable. Let me know if you run into anything, and we can take a quick look again. 

Best, Jilling
Adyen
