### ISSUE TITLE
GSON date conversion issue

### ISSUE THREAD

**Issue by vaibhav1510** [Adyen/adyen-java-api-library#118]
**Java version**: 1.8
**Library version**: 1.5.2
**GSON date conversion issue**

listRecurringDetails request not able to convert the Date format

```
com.google.gson.JsonSyntaxException: 2018-09-25T13:25:37+02:00
at com.google.gson.internal.bind.DateTypeAdapter.deserializeToDate(DateTypeAdapter.java:81)
at com.google.gson.internal.bind.DateTypeAdapter.read(DateTypeAdapter.java:66)
at com.google.gson.internal.bind.DateTypeAdapter.read(DateTypeAdapter.java:41)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172)
at com.google.gson.Gson.fromJson(Gson.java:795)
at com.google.gson.Gson.fromJson(Gson.java:761)
at com.google.gson.Gson.fromJson(Gson.java:710)
at com.adyen.service.Recurring.listRecurringDetails(Recurring.java:59)
```

**Comment by rikterbeek** [comment]
Hi @vaibhav1510,

Do have the JSON result of the API call ? If not can you provide a pspreference so we can look it up. Best to send this through our support email, support@adyen.com. 
What version of the GSON library are you using sometimes our dependency of GSON 2.8.0 is overwritten by a lower version that could be the reason.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi @vaibhav1510,

Closing this issue as there is no responds on my last question. I hope you have resolved your issue.

Regards,
Rik
Adyen
