### ISSUE TITLE
v23.0.1 throws exception when doing TerminalSettingsTerminalLevelApi.getTerminalSettings

### ISSUE THREAD

**Issue by jsyrjala** [Adyen/adyen-java-api-library#1235]
**Describe the bug**

Calling `TerminalSettingsTerminalLevelApi.getTerminalSettings` throws exception when using our Adyen test environment. 
This started to happend after we upgraded adyen-java-api-library to version from [v23.0.0](https://github.com/Adyen/adyen-java-api-library/releases/tag/v23.0.0) to [v23.0.1](https://github.com/Adyen/adyen-java-api-library/releases/tag/v23.0.1). 

Rolling back to 23.0.0 fixed the issue.

**How to reproduce**

**Expected behavior**

Expected that there is no exception. Things should work as previously.

**Desktop:**
 - Java Version: 21
 - Library Version: 23.0.1, 23.0.2

**Additional context**

Similar issue in dotnet https://github.com/Adyen/adyen-dotnet-api-library/issues/989

Stacktrace
```
com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `com.adyen.model.management.Notification$CategoryEnum`, problem: Unexpected value ''
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 532] (through reference chain: com.adyen.model.management.TerminalSettings[\"nexo\"]->com.adyen.model.management.Nexo[\"notification\"]->com.adyen.model.management.Notification[\"category\"])
	at com.fasterxml.jackson.databind.exc.ValueInstantiationException.from(ValueInstantiationException.java:47)
	at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:2014)
	at com.fasterxml.jackson.databind.DeserializationContext.handleInstantiationProblem(DeserializationContext.java:1426)
	at com.fasterxml.jackson.databind.deser.std.FactoryBasedEnumDeserializer.deserialize(FactoryBasedEnumDeserializer.java:205)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:310)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:310)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:310)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:342)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4899)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3846)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3814)
	at com.adyen.model.management.TerminalSettings.fromJson(TerminalSettings.java:836)
	at com.adyen.service.management.TerminalSettingsTerminalLevelApi.getTerminalSettings(TerminalSettingsTerminalLevelApi.java:117)
	at com.adyen.service.management.TerminalSettingsTerminalLevelApi.getTerminalSettings(TerminalSettingsTerminalLevelApi.java:95)
	at OUR_CODE
```

**Comment by jsyrjala** [comment]
Seems to me that v23.0.1 added new enum, but API actually gives empty string to that field.

https://github.com/Adyen/adyen-java-api-library/compare/v23.0.0...v23.0.1#diff-6d906527b0e3e8f4d7c512e1b63e9355885dd5b5721950631eed499f1b5d7516R42

**Comment by jillingk** [comment]
Hi @jsyrjala,

Thanks for reaching out here with this issue. The API owners internally are noticed and are taking a look at it! 

Best, Jilling
Adyen

**Comment by jsyrjala** [comment]
Same thing happens also in 23.0.2

**Comment by DjoykeAbyah** [comment]
Hi @jsyrjala!

We've just released the latest updates for Java https://github.com/Adyen/adyen-java-api-library/blob/13ff139bfb22f9a4abde57e2923bd2afb31a4f81/src/main/java/com/adyen/model/management/Notification.java#L50 These changes have also been implemented in the .Net version. This should fix the issue!  

Kind regards,

Djoyke
Adyen

**Comment by DjoykeAbyah** [comment]
Hi @jsyrjala!

We've just released the latest updates for Java https://github.com/Adyen/adyen-java-api-library/blob/13ff139bfb22f9a4abde57e2923bd2afb31a4f81/src/main/java/com/adyen/model/management/Notification.java#L50 These changes have also been implemented in the .Net version. This should fix the issue!  

Kind regards,

Djoyke
Adyen
