### ISSUE TITLE
UnsupportedOperationException on Android 5.1 after changes between v29.0.0 and v29.1.0

### ISSUE THREAD

**Issue by ibartj** [Adyen/adyen-java-api-library#1403]
**Describe the bug**
An `UnsupportedOperationException` occurs on Android 5.1 after upgrading from version `v29.0.0` to `v29.1.0` of the library when processing payments through the terminal. The issue appears to be caused by the update of `org.apache.httpcomponents.client5` from version `5.3.1` to `5.4`.

**How to reproduce**
- Use an Android 5.1 device (we are testing on Android 5.1.1).
- Attempt to complete a payment transaction.
- Observe that the payment fails, throwing the exception.

**Expected behavior**
The payment transaction should complete without any errors.

**Stacktrace**
```
java.lang.UnsupportedOperationException
	at javax.net.ssl.SSLSocket.shutdownOutput(SSLSocket.java:843)
	at org.apache.hc.core5.http.impl.io.BHttpConnectionBase.close(BHttpConnectionBase.java:252)
	at org.apache.hc.core5.http.impl.io.DefaultBHttpClientConnection.close(DefaultBHttpClientConnection.java:71)
	at org.apache.hc.client5.http.impl.io.DefaultManagedHttpClientConnection.close(DefaultManagedHttpClientConnection.java:176)
	at org.apache.hc.core5.pool.PoolEntry.discardConnection(PoolEntry.java:180)
	at org.apache.hc.core5.pool.StrictConnPool$PerRoutePool.shutdown(StrictConnPool.java:839)
	at org.apache.hc.core5.pool.StrictConnPool.close(StrictConnPool.java:142)
	at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.close(PoolingHttpClientConnectionManager.java:277)
	at org.apache.hc.client5.http.impl.classic.InternalHttpClient.close(InternalHttpClient.java:198)
	at org.apache.hc.client5.http.impl.classic.InternalHttpClient.close(InternalHttpClient.java:188)
	at com.adyen.httpclient.AdyenHttpClient.request(AdyenHttpClient.java:111)
	at com.adyen.service.resource.Resource.request(Resource.java:112)
	at com.adyen.service.resource.Resource.request(Resource.java:92)
	at com.adyen.service.resource.Resource.request(Resource.java:72)
	at com.adyen.service.TerminalLocalAPI.request(TerminalLocalAPI.java:67)
	at com.storyous.terminal.adyen.AdyenTerminal.paymentTransaction(AdyenTerminal.kt:66)
```

**Additional context**
[Release with breaking changes](https://github.com/Adyen/adyen-java-api-library/releases/tag/v29.1.0)
[Diff of changes](https://github.com/Adyen/adyen-java-api-library/compare/v29.0.0...v29.1.0)

**Comment by ibartj** [comment]
Hi @jillingk, do you think there is any chance that this will be fixed someday in the future?

**Comment by gcatanese** [comment]
Hello @ibartj, sorry to hear about the inconvenience. It looks a compatibility issue between the old Android version and the HTTP Client update.
Are you able to downgrade the Apache `httpclient5`version to `5.3.1`?

**Comment by ibartj** [comment]
Thanks, @gcatanese! I was probably afraid that the downgraded Apache Client wouldn't work, but the forced 5.3.1 seems to be working. 🚀 🙏
