### ISSUE TITLE
java.lang.IllegalArgumentException: @JsonAdapter value must be TypeAdapter or TypeAdapterFactory reference.

### ISSUE THREAD

**Issue by ionmihov** [Adyen/adyen-java-api-library#260]
**Java version**: jdk1.8.0_101
**Library version**: 2.7.0
**Description**
new customer trying to use your library with the examples from documentation 
```java
  private Client initClient() {
        Client client = new Client(apiKey, environment);

        return client;
    }

    public PaymentMethodsResponse getAvailablePaymentMethods() throws ApiException, IOException {
        Checkout checkout = new Checkout(initClient());
        PaymentMethodsRequest paymentMethodsRequest = new PaymentMethodsRequest();
        paymentMethodsRequest.setMerchantAccount("merchant name ");
        paymentMethodsRequest.setCountryCode("UK");
        Amount amount = new Amount();
        amount.setCurrency("GBP");
        amount.setValue(1000L);
        paymentMethodsRequest.setAmount(amount);
        paymentMethodsRequest.setChannel(PaymentMethodsRequest.ChannelEnum.WEB);
        PaymentMethodsResponse response = checkout.paymentMethods(paymentMethodsRequest);

        return response;
    }
```
on execution I get the following error :
```
java.lang.IllegalArgumentException: @JsonAdapter value must be TypeAdapter or TypeAdapterFactory reference.
	at com.google.gson.internal.bind.JsonAdapterAnnotationTypeAdapterFactory.getTypeAdapter(JsonAdapterAnnotationTypeAdapterFactory.java:64)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getFieldAdapter(ReflectiveTypeAdapterFactory.java:133)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.access$100(ReflectiveTypeAdapterFactory.java:49)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:106)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:105)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:161)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:97)
	at com.google.gson.Gson.getAdapter(Gson.java:360)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getFieldAdapter(ReflectiveTypeAdapterFactory.java:136)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.access$100(ReflectiveTypeAdapterFactory.java:49)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:106)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:105)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:161)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:97)
	at com.google.gson.Gson.getAdapter(Gson.java:360)
	at com.google.gson.Gson.toJson(Gson.java:597)
	at com.google.gson.Gson.toJson(Gson.java:584)
	at com.google.gson.Gson.toJson(Gson.java:539)
	at com.google.gson.Gson.toJson(Gson.java:519)
	at com.adyen.service.Checkout.paymentMethods(Checkout.java:94)
```

**Comment by ionmihov** [comment]
I found the problem , in my project there where a dependency to older version of gson library , I updated this is it resolved the issue
