### ISSUE TITLE
Unable to deserialize response from /v68/listRecurringDetails

### ISSUE THREAD

**Issue by jrparker** [Adyen/adyen-java-api-library#986]
**Describe the bug**

While upgrading to version 19.0.0 of the Adyen SDK, I encountered a regression that prevents  deserialization of the response from a call to `.../v68/listRecurringDetails` into a `RecurringDetailsResult` object.

The response from that endpoint looks like:
```json
{
  "creationDate": "2023-03-22T20:26:30+01:00",
  "details": [
    {
      "RecurringDetail": {
        "additionalData": {
          "cardBin": "123456"
        },
        "alias": "H533081399650980",
        "aliasType": "Default",
        "billingAddress": {
          "city": "NW Washington",
          "country": "US",
          "houseNumberOrName": "1600",
          "postalCode": "20500",
          "stateOrProvince": "DC",
          "street": "Pennsylvania Ave"
        },
        "card": {
          "expiryMonth": "3",
          "expiryYear": "2030",
          "holderName": "John Smith",
          "number": "0004"
        },
        "contractTypes": [
          "ONECLICK",
          "RECURRING",
          "PAYOUT"
        ],
        "creationDate": "2023-03-22T20:26:30+01:00",
        "firstPspReference": "F3PJVJR9C75ZGN82",
        "name": "123321",
        "networkTxReference": "XPOUX3QFR03220322",
        "paymentMethodVariant": "mcdebit",
        "recurringDetailReference": "PM6H6R3ZN6KXWD82",
        "variant": "mc"
      }
    }
  ],
  "shopperReference": "abc123"
}

```

But I am experiencing an exception similar to the following as the SDK tries to deserialize the response with Gson:

```
java.lang.IllegalArgumentException: The field `RecurringDetail` in the JSON string is not defined in the `RecurringDetail` properties. JSON: {"RecurringDetail":{"additionalData":{"cardBin":"123456"},"alias":"H533081399650980","aliasType":"Default","billingAddress":{"city":"NW Washington","country":"US","houseNumberOrName":"1600","postalCode":"20500","stateOrProvince":"DC","street":"Pennsylvania Ave"},"card":{"expiryMonth":"3","expiryYear":"2030","holderName":"John Smith","number":"0004"},"contractTypes":["ONECLICK","RECURRING","PAYOUT"],"creationDate":"2023-03-22T20:26:30+01:00","firstPspReference":"F3PJVJR9C75ZGN82","name":"123321","networkTxReference":"XPOUX3QFR03220322","paymentMethodVariant":"mcdebit","recurringDetailReference":"PM6H6R3ZN6KXWD82","variant":"mc"}}

	at com.adyen.model.recurring.RecurringDetail.validateJsonObject(RecurringDetail.java:642)
	at com.adyen.model.recurring.RecurringDetailsResult.validateJsonObject(RecurringDetailsResult.java:261)
	at com.adyen.model.recurring.RecurringDetailsResult$CustomTypeAdapterFactory$1.read(RecurringDetailsResult.java:295)
	at com.adyen.model.recurring.RecurringDetailsResult$CustomTypeAdapterFactory$1.read(RecurringDetailsResult.java:285)
```

Looking at the code history, it appears that changes in https://github.com/Adyen/adyen-java-api-library/pull/830 removed a `RecurringDetailContainer` wrapper object linked to the "RecurringDetail" JSON node, and added the `validateJsonObject()` methods to `RecurringDetail` and `RecurringDetailsResult` that are now throwing the exception above.

**How to reproduce**

This should be reproducible with any call to the `listRecurringDetails` endpoint with v19.0.0 of the Adyen SDK.

**Desktop (please complete the following information):**

 - Java Version: 11.0.18
 - Library Version: 19.0.0

**Comment by jrparker** [comment]
I was thinking about creating a PR to address this issue, but the code changes from https://github.com/Adyen/adyen-java-api-library/pull/830 are from generated code, correct?

**Comment by jrparker** [comment]
I see that [this issue](https://github.com/Adyen/adyen-openapi/pull/36) has been raised in https://github.com/Adyen/adyen-openapi, so it sounds like this problem will be addressed at the openapi spec level.
